---
title: "Wrangle RAM Legacy Stock Database"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scales)
library(ggrepel)
library(knitr) 

# Path to raw RAM .Rdata
ram_dat_path <- "./RAM v4.491 Files (1-14-20)/RAM v4.491/DB Files With Assessment Data/R Data/DBdata[asmt][v4.491].RData"

# Load RAM data
load(ram_dat_path)

# Load FAO areas cooresponding to RAM stocks
fao_areas_for_ram <- read_csv("fao_areas_for_ram_stocks_v4.491.csv")

# Directories for the output files generated by this script
results_dir <- here::here("figures", "ram-data-visualization/")
if (dir.exists(results_dir) == F) {
  dir.create(results_dir, recursive = T)
}

```

## Extract B/Bmsy

For the purposes of this analysis, we're only interested in stocks that have reference points. Notable B/Bmsy and F/Fmsy. We start by extracting B/Bmsy and applying the FAO regions we used above. 

```{r}
# Bvbmsy
bvbmsy <- divbpref.data %>%
  rownames_to_column(var = "year") %>%
  gather(stockid, bv_bmsy, -year) %>%
  dplyr::filter(!is.na(bv_bmsy)) %>%
  mutate(year = as.numeric(year))

# Get most recent estimate of B/Bmsy for each stock
bvbmsy_mry <- bvbmsy %>%
  group_by(stockid) %>%
  mutate(mry_year = max(year)) %>%
  ungroup() %>%
  dplyr::filter(year == mry_year) %>%
  dplyr::select(-mry_year, -year)
```

## Extract F/Fmsy

```{r}
# FvFmsy
fvfmsy <- divf.data %>%
  rownames_to_column(var = "year") %>%
  gather(stockid, fv_fmsy, -year) %>%
  dplyr::filter(!is.na(fv_fmsy)) %>%
  mutate(year = as.numeric(year))

# Get most recent estimate of B/Bmsy for each stock
fvfmsy_mry <- fvfmsy %>%
  group_by(stockid) %>%
  mutate(mry_year = max(year)) %>%
  ungroup() %>%
  dplyr::filter(year == mry_year) %>%
  dplyr::select(-mry_year, -year)
```

## Extract MSY

```{r}
# Msy
msy <- bioparams_values_views %>%
  dplyr::select(stockid,
                stocklong,
                msy = MSYbest)
```

## Combine and match to FAO areas

```{r}
ram_dat_out <- msy %>%
  left_join(bvbmsy_mry, by = "stockid") %>%
  left_join(fvfmsy_mry, by = "stockid") %>%
  na.omit() %>%
  left_join(fao_areas_for_ram, by = "stockid") %>%
  mutate(region_fao_split = str_split(fao_area, ";")) %>%
  group_by(stockid) %>%
  mutate(n_regions = length(region_fao_split[[1]])) %>%
  ungroup() %>%
  unnest(cols = c(region_fao_split)) %>%
  mutate(fao_region = as.numeric(region_fao_split)) %>%
  mutate(msy = msy/n_regions)

write_csv(ram_dat_out, "ram_v4.491_ref_points_fao_area_tidy.csv")
```

## Make plots by FAO area to see which stocks are driving results

```{r}

kobe_plot_fao_region <- ram_dat_out %>%
  ggplot(aes(x = bv_bmsy, y = fv_fmsy, group = stockid, size = msy/1e6))+
  annotate("rect", xmin = 0, xmax = 1, ymin = 0, ymax = 1, fill = "yellow", alpha = 0.3)+
  annotate("rect", xmin = 1, xmax = 5, ymin = 0, ymax = 1, fill = "green", alpha = 0.3)+
  annotate("rect", xmin = 0, xmax = 1, ymin = 1, ymax = 5, fill = "red", alpha = 0.3)+
  annotate("rect", xmin = 1, xmax = 5, ymin = 1, ymax = 5, fill = "yellow", alpha = 0.3)+
  geom_point() +
  scale_x_continuous(limits = c(0,5), oob = squish)+
  scale_y_continuous(limits = c(0,5), oob = squish)+
  labs(x = "B/Bmsy", y = "F/Fmsy", size = "MSY (million mt)") +
  facet_wrap(~as.factor(fao_region), ncol = 3)+
  theme_bw()


kobe_plot_fao_region
  
ggsave(paste0(results_dir, "kobe_plot_fao_region_all.png"), kobe_plot_fao_region, width = 8.5, height = 11, units = "in")
```

```{r}
regions <- sort(unique(ram_dat_out$fao_region))

for(i in 1:length(regions)){
  
  plot_region <- regions[i]
  
  plot <- ram_dat_out %>%
    mutate(over = case_when(bv_bmsy > 5 ~ "Yes",
                            fv_fmsy > 5 ~ "Yes",
                            TRUE ~ "No")) %>%
    dplyr::filter(fao_region == plot_region) %>%
    ggplot(aes(x = bv_bmsy, y = fv_fmsy, group = stockid, size = msy/1e6, color = over))+
    annotate("rect", xmin = 0, xmax = 1, ymin = 0, ymax = 1, fill = "yellow", alpha = 0.3)+
    annotate("rect", xmin = 1, xmax = 5, ymin = 0, ymax = 1, fill = "green", alpha = 0.3)+
    annotate("rect", xmin = 0, xmax = 1, ymin = 1, ymax = 5, fill = "red", alpha = 0.3)+
    annotate("rect", xmin = 1, xmax = 5, ymin = 1, ymax = 5, fill = "yellow", alpha = 0.3)+
    geom_point() +
    geom_text_repel(aes(label = stockid), color = "black", size = 2, force = 2)+
    scale_x_continuous(limits = c(0,5), oob = squish)+
    scale_y_continuous(limits = c(0,5), oob = squish)+
    labs(x = "B/Bmsy", y = "F/Fmsy", title = paste0("FAO Area ", plot_region)) +
    guides(size = "none",
           color = "none")+
    theme_bw()+
    scale_color_manual(values = c("black", "red"))

ggsave(paste0(results_dir, "kobe_plot_fao_region_", plot_region, ".png"), plot, width = 8.5, height = 8.5, units = "in")
}
```

